include/Ackermann.hh File Reference
Ackermann库
#include `Stack.hh`
#include <climits>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <iomanip>
#include <iostream>
Classes
class Akm_t
Functions
int Ackermann (int m, int n)
int AckermannLoop (int m, int n)
Variables
static int Akm_deep = 0
static int deep_max = 0
Detailed Description
Ackermann库
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-04-05
Copyright
Copyright (c) 2020
Function Documentation
Ackermann()
int Ackermann (int m, int n)
Definition at line 70 of file Ackermann.hh.
References Akm_deep, and deep_max.
Referenced by Akm_t::Akm_rec().
AckermannLoop()
int AckermannLoop (int m, int n)
Definition at line 99 of file Ackermann.hh.
References Akm_deep, deep_max, Stack::seqStack< T >::elemMem(), Stack::seqStack< T >::isEmpty(), Stack::seqStack< T >::pop(), Stack::seqStack< T >::push(), Stack::seqStack< T >::size(), and Stack::seqStack< T >::top().
Referenced by Akm_t::Akm_loop().
Variable Documentation
Akm_deep
int Akm_deep = 0 [static]
Definition at line 26 of file Ackermann.hh.
Referenced by Ackermann(), AckermannLoop(), and Akm_t::Akm_rec().
deep_max
int deep_max = 0 [static]
Definition at line 27 of file Ackermann.hh.
Referenced by Ackermann(), AckermannLoop(), and Akm_t::Akm_rec().