src/ch3_5.cc File Reference
后缀表达式的计算
#include `Rpn.hh`
#include <cstring>
#include <ctime>
Functions
int main (int argc, char const *argv[])
Detailed Description
后缀表达式的计算
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-04-05
Copyright
Copyright (c) 2020
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 16 of file ch3_5.cc.
References RPN::Rpn_t::assign(), RPN::buf_size, RPN::Rpn_t::calcVal(), RPN::Postfix, and RPN::Rpn_t::postfix().