List::dLinkList< T > Class Template Reference
#include <dLinkList.h>
Classes
class const_iterator
class iterator
struct node
Public Member Functions
dLinkList ()
dLinkList (const dLinkList< T > &rhs)
dLinkList (dLinkList< T > &&rvalue)
dLinkList< T > & operator= (dLinkList< T > &&rvalue)
~dLinkList ()
virtual void clear ()
virtual int length () const
virtual void insert (int i, const T &obj)
virtual void remove (int i)
virtual int search (const T &obj) const
virtual T visit (int i) const
virtual void traverse () const =delete
virtual iterator begin ()
virtual const_iterator begin () const
void push_back (const T &obj)
void push_back (T &&obj)
void pop_back ()
const T & back () const
T & back ()
virtual iterator end ()
virtual const_iterator end () const
Private Member Functions
node * move (int i) const
Private Attributes
node * head
node * tail
int currentLength
Friends
dLinkList< T > operator+ (const dLinkList< T > &A, const dLinkList< T > &B)
Detailed Description
template<typename T>
class List::dLinkList< T >
Definition at line 23 of file dLinkList.h.
Constructor & Destructor Documentation
dLinkList() [1/3]
template<class T >
List::dLinkList< T >::dLinkList
Definition at line 174 of file dLinkList.h.
dLinkList() [2/3]
template<class T >
List::dLinkList< T >::dLinkList (const dLinkList< T > & rhs)
Definition at line 189 of file dLinkList.h.
dLinkList() [3/3]
template<class T >
List::dLinkList< T >::dLinkList (dLinkList< T > && rvalue)
Definition at line 182 of file dLinkList.h.
 dLinkList()
template<typename T >
List::dLinkList< T >::~dLinkList () [inline]
Definition at line 118 of file dLinkList.h.
Member Function Documentation
back() [1/2]
template<typename T >
T& List::dLinkList< T >::back () [inline]
Definition at line 142 of file dLinkList.h.
back() [2/2]
template<typename T >
const T& List::dLinkList< T >::back () const [inline]
Definition at line 141 of file dLinkList.h.
begin() [1/2]
template<typename T >
virtual iterator List::dLinkList< T >::begin () [inline], [virtual]
Definition at line 136 of file dLinkList.h.
Referenced by List::dLinkList< RPN::Rpn_t::Item >::dLinkList(), and RPN::Rpn_t::infixListToPostfixList().
begin() [2/2]
template<typename T >
virtual const_iterator List::dLinkList< T >::begin () const [inline], [virtual]
Definition at line 137 of file dLinkList.h.
clear()
template<class T >
void List::dLinkList< T >::clear [virtual]
Definition at line 244 of file dLinkList.h.
Referenced by List::dLinkList< RPN::Rpn_t::Item >::~dLinkList().
end() [1/2]
template<typename T >
virtual iterator List::dLinkList< T >::end () [inline], [virtual]
Definition at line 145 of file dLinkList.h.
Referenced by List::dLinkList< RPN::Rpn_t::Item >::dLinkList(), and RPN::Rpn_t::infixListToPostfixList().
end() [2/2]
template<typename T >
virtual const_iterator List::dLinkList< T >::end () const [inline], [virtual]
Definition at line 146 of file dLinkList.h.
insert()
template<class T >
void List::dLinkList< T >::insert (int i, const T & obj) [virtual]
Definition at line 222 of file dLinkList.h.
length()
template<class T >
int List::dLinkList< T >::length [virtual]
Definition at line 206 of file dLinkList.h.
move()
template<class T >
dLinkList< T >::node * List::dLinkList< T >::move (int i) const [private]
Definition at line 212 of file dLinkList.h.
operator=()
template<class T >
dLinkList< T > & List::dLinkList< T >::operator= (dLinkList< T > && rvalue)
Definition at line 197 of file dLinkList.h.
pop_back()
template<class T >
void List::dLinkList< T >::pop_back
Definition at line 317 of file dLinkList.h.
push_back() [1/2]
template<class T >
void List::dLinkList< T >::push_back (const T & obj)
Definition at line 304 of file dLinkList.h.
Referenced by RPN::Rpn_t::infixListToPostfixList(), and List::operator+().
push_back() [2/2]
template<class T >
void List::dLinkList< T >::push_back (T && obj)
Definition at line 310 of file dLinkList.h.
remove()
template<class T >
void List::dLinkList< T >::remove (int i) [virtual]
Definition at line 232 of file dLinkList.h.
search()
template<class T >
int List::dLinkList< T >::search (const T & obj) const [virtual]
Definition at line 265 of file dLinkList.h.
traverse()
template<typename T >
virtual void List::dLinkList< T >::traverse () const [virtual], [delete]
visit()
template<class T >
T List::dLinkList< T >::visit (int i) const [virtual]
Definition at line 283 of file dLinkList.h.
Friends And Related Function Documentation
operator+
template<typename T >
dLinkList<T> operator+ (const dLinkList< T > & A, const dLinkList< T > & B) [friend]
Definition at line 151 of file dLinkList.h.
Member Data Documentation
currentLength
template<typename T >
int List::dLinkList< T >::currentLength [private]
Definition at line 47 of file dLinkList.h.
head
template<typename T >
node* List::dLinkList< T >::head [private]
Definition at line 46 of file dLinkList.h.
Referenced by List::dLinkList< RPN::Rpn_t::Item >::begin(), List::operator+(), and List::dLinkList< RPN::Rpn_t::Item >::~dLinkList().
tail
template<typename T >
node * List::dLinkList< T >::tail [private]
Definition at line 46 of file dLinkList.h.
Referenced by List::dLinkList< RPN::Rpn_t::Item >::back(), List::dLinkList< RPN::Rpn_t::Item >::end(), List::operator+(), and List::dLinkList< RPN::Rpn_t::Item >::~dLinkList().
The documentation for this class was generated from the following file:
include/dLinkList.h