Stack::linkStack< T > Class Template Reference
#include <linkStack.hpp>
Classes
struct node
Public Member Functions
linkStack ()
linkStack (std::initializer_list< T > &&il)
virtual bool isEmpty () const
virtual void push (const T &elem)
virtual void push (T &&elem)
virtual T pop ()
virtual T top () const
virtual ~linkStack ()
Private Attributes
node * top_p
Detailed Description
template<typename T>
class Stack::linkStack< T >
Definition at line 21 of file linkStack.hpp.
Constructor & Destructor Documentation
linkStack() [1/2]
template<class T >
Stack::linkStack< T >::linkStack
Definition at line 51 of file linkStack.hpp.
linkStack() [2/2]
template<class T >
Stack::linkStack< T >::linkStack (std::initializer_list< T > && il)
Definition at line 57 of file linkStack.hpp.
References Stack::linkStack< T >::push().
 linkStack()
template<class T >
Stack::linkStack< T >::~linkStack [virtual]
Definition at line 65 of file linkStack.hpp.
Member Function Documentation
isEmpty()
template<class T >
bool Stack::linkStack< T >::isEmpty [virtual]
Implements Stack::Stack< T >.
Definition at line 106 of file linkStack.hpp.
Referenced by ch3_3::permuteWithFixedPrefix_Loop().
pop()
template<class T >
T Stack::linkStack< T >::pop [virtual]
Implements Stack::Stack< T >.
Definition at line 88 of file linkStack.hpp.
Referenced by RPN::Rpn_t::infixListToPostfixList(), and ch3_3::permuteWithFixedPrefix_Loop().
push() [1/2]
template<class T >
void Stack::linkStack< T >::push (const T & elem) [virtual]
Implements Stack::Stack< T >.
Definition at line 76 of file linkStack.hpp.
Referenced by RPN::Rpn_t::infixListToPostfixList(), Stack::linkStack< T >::linkStack(), ch3_3::permuteWithFixedPrefix_Loop(), and prnUIntInBin().
push() [2/2]
template<class T >
void Stack::linkStack< T >::push (T && elem) [virtual]
Definition at line 82 of file linkStack.hpp.
top()
template<class T >
T Stack::linkStack< T >::top [virtual]
Implements Stack::Stack< T >.
Definition at line 100 of file linkStack.hpp.
Referenced by RPN::Rpn_t::infixListToPostfixList(), and ch3_3::permuteWithFixedPrefix_Loop().
Member Data Documentation
top_p
template<typename T >
node* Stack::linkStack< T >::top_p [private]
Definition at line 37 of file linkStack.hpp.
The documentation for this class was generated from the following file:
include/linkStack.hpp