Stack::seqStack< T > Class Template Reference
#include <seqStack.hxx>
Public Member Functions
seqStack (int initSize=10)
seqStack (std::initializer_list< T > &&il)
virtual bool isEmpty () const
virtual void push (const T &elem)
virtual void push (T &&elem)
virtual T pop ()
virtual T top () const
int size () const
int elemMem () const
virtual ~seqStack ()
Private Member Functions
void doubleSpace ()
Private Attributes
T * elem
int top_p
int maxSize
Detailed Description
template<class T>
class Stack::seqStack< T >
Definition at line 22 of file seqStack.hxx.
Constructor & Destructor Documentation
seqStack() [1/2]
template<class T >
Stack::seqStack< T >::seqStack (int initSize = 10)
Definition at line 44 of file seqStack.hxx.
seqStack() [2/2]
template<class T >
Stack::seqStack< T >::seqStack (std::initializer_list< T > && il)
Definition at line 50 of file seqStack.hxx.
References Stack::seqStack< T >::elem, and Stack::seqStack< T >::top_p.
 seqStack()
template<class T >
Stack::seqStack< T >::~seqStack [virtual]
Definition at line 58 of file seqStack.hxx.
Member Function Documentation
doubleSpace()
template<class T >
void Stack::seqStack< T >::doubleSpace [private]
Definition at line 100 of file seqStack.hxx.
elemMem()
template<class T >
int Stack::seqStack< T >::elemMem
Definition at line 118 of file seqStack.hxx.
Referenced by Akm_t::AckermannLoop().
isEmpty()
template<class T >
bool Stack::seqStack< T >::isEmpty [virtual]
Implements Stack::Stack< T >.
Definition at line 64 of file seqStack.hxx.
Referenced by Akm_t::AckermannLoop(), and RPN::Rpn_t::calcVal().
pop()
template<class T >
T Stack::seqStack< T >::pop [virtual]
Implements Stack::Stack< T >.
Definition at line 88 of file seqStack.hxx.
Referenced by Akm_t::AckermannLoop(), and RPN::Rpn_t::calcVal().
push() [1/2]
template<class T >
void Stack::seqStack< T >::push (const T & elem) [virtual]
Implements Stack::Stack< T >.
Definition at line 70 of file seqStack.hxx.
Referenced by Akm_t::AckermannLoop(), and RPN::Rpn_t::calcVal().
push() [2/2]
template<class T >
void Stack::seqStack< T >::push (T && elem) [virtual]
Definition at line 79 of file seqStack.hxx.
size()
template<class T >
int Stack::seqStack< T >::size
Definition at line 112 of file seqStack.hxx.
Referenced by Akm_t::AckermannLoop().
top()
template<class T >
T Stack::seqStack< T >::top [virtual]
Implements Stack::Stack< T >.
Definition at line 94 of file seqStack.hxx.
Referenced by Akm_t::AckermannLoop().
Member Data Documentation
elem
template<class T >
T* Stack::seqStack< T >::elem [private]
Definition at line 25 of file seqStack.hxx.
Referenced by Stack::seqStack< T >::seqStack().
maxSize
template<class T >
int Stack::seqStack< T >::maxSize [private]
Definition at line 27 of file seqStack.hxx.
top_p
template<class T >
int Stack::seqStack< T >::top_p [private]
Definition at line 26 of file seqStack.hxx.
Referenced by Stack::seqStack< T >::seqStack().
The documentation for this class was generated from the following file:
include/seqStack.hxx