src/ch3_2.cc File Reference
#include `Stack.hh`
#include <iostream>
#include <string>
Functions
void prnNonNegDecInBin (unsigned long dec=0)
int main (int argc, char const *argv[])
Detailed Description
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-04-05
Copyright
Copyright (c) 2020
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 18 of file ch3_2.cc.
References prnNonNegDecInBin().
prnNonNegDecInBin()
void prnNonNegDecInBin (unsigned long dec = 0)
Definition at line 45 of file ch3_2.cc.
References Stack::linkStack< T >::push().
Referenced by main().