src/ch3_7.cc File Reference
#include `Ackermann.hh`
Functions
static void Akm_loop (int x, int y)
static void Akm_rec (int x, int y)
int main (int argc, char const *argv[])
Detailed Description
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-04-05
Copyright
Copyright (c) 2020
Function Documentation
Akm_loop()
void Akm_loop (int x, int y) [static]
Definition at line 77 of file ch3_7.cc.
References AckermannLoop().
Referenced by main().
Akm_rec()
void Akm_rec (int x, int y) [static]
Definition at line 90 of file ch3_7.cc.
References Ackermann(), Akm_deep, and deep_max.
Referenced by main().
main()
int main (int argc, char const * argv[])
Definition at line 17 of file ch3_7.cc.
References Akm_loop(), and Akm_rec().