Akm_t Class Reference
#include <Ackermann.hh>
Public Member Functions
Akm_t (std::string name=`name`)
~Akm_t ()=default
Static Public Member Functions
static void Akm_loop (int x, int y)
static void Akm_rec (int x, int y)
Private Attributes
std::string _name
Detailed Description
Definition at line 29 of file Ackermann.hh.
Constructor & Destructor Documentation
Akm_t()
Akm_t::Akm_t (std::string name = `name`) [inline]
Definition at line 35 of file Ackermann.hh.
 Akm_t()
Akm_t::~Akm_t () [default]
Member Function Documentation
Akm_loop()
void Akm_t::Akm_loop (int x, int y) [static]
Definition at line 41 of file Ackermann.hh.
References AckermannLoop().
Referenced by main().
Akm_rec()
void Akm_t::Akm_rec (int x, int y) [static]
Definition at line 54 of file Ackermann.hh.
References Ackermann(), Akm_deep, and deep_max.
Referenced by main().
Member Data Documentation
_name
std::string Akm_t::_name [private]
Definition at line 32 of file Ackermann.hh.
The documentation for this class was generated from the following file:
include/Ackermann.hh