ch3_3 Namespace Reference
Functions
template<class T >
void swap (T &a, T &b)
template<class BidirIt >
void reverse (BidirIt first, BidirIt last)
template<class BidirIt >
void permuteWithFixedPrefix (BidirIt first, BidirIt last, BidirIt fixPos)
template<class BidirIt >
void permuteWithFixedPrefix_Loop (BidirIt first, BidirIt last, BidirIt fixPos)
template<class T >
void permute_rec (const T &_s)
template<class T >
void permute_loop (const T &_s)
template<class BidirIt >
bool next_perm (BidirIt first, BidirIt last)
template<class T >
void permute_stl (const T &_s)
Function Documentation
next_perm()
template<class BidirIt >
bool ch3_3::next_perm (BidirIt first, BidirIt last)
Definition at line 209 of file Permute.hh.
References reverse(), and swap().
Referenced by permute_stl().
permute_loop()
template<class T >
void ch3_3::permute_loop (const T & _s)
Definition at line 197 of file Permute.hh.
References permuteWithFixedPrefix_Loop().
Referenced by main().
permute_rec()
template<class T >
void ch3_3::permute_rec (const T & _s)
Definition at line 186 of file Permute.hh.
References permuteWithFixedPrefix().
Referenced by main().
permute_stl()
template<class T >
void ch3_3::permute_stl (const T & _s)
Definition at line 241 of file Permute.hh.
References next_perm().
Referenced by main().
permuteWithFixedPrefix()
template<class BidirIt >
void ch3_3::permuteWithFixedPrefix (BidirIt first, BidirIt last, BidirIt fixPos)
Definition at line 46 of file Permute.hh.
References swap().
Referenced by permute_rec().
permuteWithFixedPrefix_Loop()
template<class BidirIt >
void ch3_3::permuteWithFixedPrefix_Loop (BidirIt first, BidirIt last, BidirIt fixPos)
Definition at line 93 of file Permute.hh.
References Stack::linkStack< T >::isEmpty(), Stack::linkStack< T >::pop(), Stack::linkStack< T >::push(), swap(), and Stack::linkStack< T >::top().
Referenced by permute_loop().
reverse()
template<class BidirIt >
void ch3_3::reverse (BidirIt first, BidirIt last)
Definition at line 37 of file Permute.hh.
References swap().
Referenced by next_perm().
swap()
template<class T >
void ch3_3::swap (T & a, T & b)
Definition at line 27 of file Permute.hh.
Referenced by next_perm(), List::dLinkList< RPN::Rpn_t::Item >::operator=(), permuteWithFixedPrefix(), permuteWithFixedPrefix_Loop(), and reverse().