List Namespace Reference
Classes
class dLinkList
class List
class seqList
class sLinkList
Functions
template<class T >
dLinkList< T > operator+ (const dLinkList< T > &A, const dLinkList< T > &B)
template<class T >
seqList< T > operator+ (const seqList< T > &A, const seqList< T > &B)
Function Documentation
operator+() [1/2]
template<class T >
dLinkList< T > List::operator+ (const dLinkList< T > & A, const dLinkList< T > & B)
Definition at line 115 of file dLinkList.h.
References List::dLinkList< T >::node::data, List::dLinkList< T >::head, List::dLinkList< T >::node::next, List::dLinkList< T >::push_back(), and List::dLinkList< T >::tail.
operator+() [2/2]
template<class T >
seqList<T> List::operator+ (const seqList< T > & A, const seqList< T > & B)
Definition at line 174 of file seqList.h.
References List::seqList< T >::insert(), List::seqList< T >::length(), and List::seqList< T >::visit().