List::dLinkList< T > Class Template Reference
#include <dLinkList.h>
Classes
class const_iterator
class iterator
struct node
Public Member Functions
dLinkList ()
~dLinkList ()
virtual void clear ()
virtual int length () const
virtual void insert (int i, const T &obj)
virtual void remove (int i)
virtual int search (const T &obj) const
virtual T visit (int i) const
virtual void traverse () const
void push_back (const T &obj)
virtual iterator begin ()
virtual const_iterator begin () const
virtual iterator end ()
virtual const_iterator end () const
Private Member Functions
node * move (int i) const
Private Attributes
node * head
node * tail
int currentLength
Friends
dLinkList< T > operator+ (const dLinkList< T > &A, const dLinkList< T > &B)
Detailed Description
template<typename T>
class List::dLinkList< T >
Definition at line 11 of file dLinkList.h.
Constructor & Destructor Documentation
dLinkList()
template<class T >
List::dLinkList< T >::dLinkList
Definition at line 138 of file dLinkList.h.
References List::dLinkList< T >::head, List::dLinkList< T >::node::next, List::dLinkList< T >::node::prev, and List::dLinkList< T >::tail.
 dLinkList()
template<typename T >
List::dLinkList< T >::~dLinkList () [inline]
Definition at line 89 of file dLinkList.h.
References List::dLinkList< T >::clear(), List::dLinkList< T >::head, and List::dLinkList< T >::tail.
Member Function Documentation
begin() [1/2]
template<typename T >
virtual iterator List::dLinkList< T >::begin () [inline], [virtual]
Definition at line 106 of file dLinkList.h.
References List::dLinkList< T >::head, and List::dLinkList< T >::node::next.
begin() [2/2]
template<typename T >
virtual const_iterator List::dLinkList< T >::begin () const [inline], [virtual]
Definition at line 107 of file dLinkList.h.
References List::dLinkList< T >::head, and List::dLinkList< T >::node::next.
clear()
template<class T >
void List::dLinkList< T >::clear [virtual]
Definition at line 184 of file dLinkList.h.
References List::dLinkList< T >::node::next, and List::dLinkList< T >::node::prev.
Referenced by List::dLinkList< T >::~dLinkList().
end() [1/2]
template<typename T >
virtual iterator List::dLinkList< T >::end () [inline], [virtual]
Definition at line 109 of file dLinkList.h.
References List::dLinkList< T >::tail.
end() [2/2]
template<typename T >
virtual const_iterator List::dLinkList< T >::end () const [inline], [virtual]
Definition at line 110 of file dLinkList.h.
References List::dLinkList< T >::tail.
insert()
template<class T >
void List::dLinkList< T >::insert (int i, const T & obj) [virtual]
Definition at line 162 of file dLinkList.h.
References List::dLinkList< T >::node::next, and List::dLinkList< T >::node::prev.
Referenced by main().
length()
template<class T >
int List::dLinkList< T >::length [virtual]
Definition at line 146 of file dLinkList.h.
move()
template<class T >
dLinkList< T >::node * List::dLinkList< T >::move (int i) const [private]
Definition at line 152 of file dLinkList.h.
References List::dLinkList< T >::node::next.
push_back()
template<class T >
void List::dLinkList< T >::push_back (const T & obj)
Definition at line 241 of file dLinkList.h.
Referenced by List::operator+().
remove()
template<class T >
void List::dLinkList< T >::remove (int i) [virtual]
Definition at line 172 of file dLinkList.h.
References List::dLinkList< T >::node::next, and List::dLinkList< T >::node::prev.
search()
template<class T >
int List::dLinkList< T >::search (const T & obj) const [virtual]
Definition at line 202 of file dLinkList.h.
References List::dLinkList< T >::node::data, and List::dLinkList< T >::node::next.
traverse()
template<class T >
void List::dLinkList< T >::traverse [virtual]
Definition at line 226 of file dLinkList.h.
References List::dLinkList< T >::node::data, and List::dLinkList< T >::node::next.
Referenced by main().
visit()
template<class T >
T List::dLinkList< T >::visit (int i) const [virtual]
Definition at line 220 of file dLinkList.h.
Friends And Related Function Documentation
operator+
template<typename T >
dLinkList<T> operator+ (const dLinkList< T > & A, const dLinkList< T > & B) [friend]
Definition at line 115 of file dLinkList.h.
Member Data Documentation
currentLength
template<typename T >
int List::dLinkList< T >::currentLength [private]
Definition at line 32 of file dLinkList.h.
head
template<typename T >
node* List::dLinkList< T >::head [private]
Definition at line 31 of file dLinkList.h.
Referenced by List::dLinkList< T >::begin(), List::dLinkList< T >::dLinkList(), List::operator+(), and List::dLinkList< T >::~dLinkList().
tail
template<typename T >
node * List::dLinkList< T >::tail [private]
Definition at line 31 of file dLinkList.h.
Referenced by List::dLinkList< T >::dLinkList(), List::dLinkList< T >::end(), List::operator+(), and List::dLinkList< T >::~dLinkList().
The documentation for this class was generated from the following file:
include/dLinkList.h