List::seqList< T > Class Template Reference
#include <seqList.h>
Classes
class const_iterator
class iterator
Public Member Functions
seqList (int initSize=10)
virtual ~seqList ()
virtual void clear ()
virtual int length () const
virtual void insert (int i, const T &obj)
virtual void remove (int i)
virtual int search (const T &obj) const
virtual T visit (int i) const
virtual void traverse () const
virtual iterator begin ()
virtual const_iterator begin () const
virtual iterator end ()
virtual const_iterator end () const
Private Member Functions
void doubleSpace ()
Private Attributes
T * data
int currentLength
int maxSize
Detailed Description
template<typename T>
class List::seqList< T >
Definition at line 11 of file seqList.h.
Constructor & Destructor Documentation
seqList()
template<class T >
List::seqList< T >::seqList (int initSize = 10)
Definition at line 126 of file seqList.h.
 seqList()
template<class T >
List::seqList< T >::~seqList [virtual]
Definition at line 92 of file seqList.h.
Member Function Documentation
begin() [1/2]
template<typename T >
virtual iterator List::seqList< T >::begin () [inline], [virtual]
Definition at line 84 of file seqList.h.
References List::seqList< T >::data.
begin() [2/2]
template<typename T >
virtual const_iterator List::seqList< T >::begin () const [inline], [virtual]
Definition at line 85 of file seqList.h.
References List::seqList< T >::data.
clear()
template<class T >
void List::seqList< T >::clear [virtual]
Implements List::List< T >.
Definition at line 98 of file seqList.h.
doubleSpace()
template<class T >
void List::seqList< T >::doubleSpace [private]
Definition at line 143 of file seqList.h.
end() [1/2]
template<typename T >
virtual iterator List::seqList< T >::end () [inline], [virtual]
Definition at line 86 of file seqList.h.
References List::seqList< T >::currentLength, and List::seqList< T >::data.
end() [2/2]
template<typename T >
virtual const_iterator List::seqList< T >::end () const [inline], [virtual]
Definition at line 87 of file seqList.h.
References List::seqList< T >::currentLength, and List::seqList< T >::data.
insert()
template<class T >
void List::seqList< T >::insert (int i, const T & obj) [virtual]
Implements List::List< T >.
Definition at line 154 of file seqList.h.
Referenced by main(), and List::operator+().
length()
template<class T >
int List::seqList< T >::length [virtual]
Implements List::List< T >.
Definition at line 104 of file seqList.h.
Referenced by List::operator+().
remove()
template<class T >
void List::seqList< T >::remove (int i) [virtual]
Implements List::List< T >.
Definition at line 166 of file seqList.h.
search()
template<class T >
int List::seqList< T >::search (const T & obj) const [virtual]
Implements List::List< T >.
Definition at line 133 of file seqList.h.
traverse()
template<class T >
void List::seqList< T >::traverse [virtual]
Implements List::List< T >.
Definition at line 116 of file seqList.h.
visit()
template<class T >
T List::seqList< T >::visit (int i) const [virtual]
Implements List::List< T >.
Definition at line 110 of file seqList.h.
Referenced by List::operator+().
Member Data Documentation
currentLength
template<typename T >
int List::seqList< T >::currentLength [private]
Definition at line 15 of file seqList.h.
Referenced by List::seqList< T >::end().
data
template<typename T >
T* List::seqList< T >::data [private]
Definition at line 14 of file seqList.h.
Referenced by List::seqList< T >::begin(), and List::seqList< T >::end().
maxSize
template<typename T >
int List::seqList< T >::maxSize [private]
Definition at line 16 of file seqList.h.
The documentation for this class was generated from the following file:
include/seqList.h