src/test0.cc File Reference
#include `test0.hh`
Functions
int main (int argc, char const *argv[])
二叉链表实现的二叉树类(binaryTree)的测试例程
Function Documentation
main()
int main (int argc, char const * argv[])
二叉链表实现的二叉树类(binaryTree)的测试例程
Parameters
argc 命令行参数的数目
argv 命令行参数的内容
Returns
int 0-正常
Warning
要求.exe对其所在的目录有读写权限
部分测试结果将输出到一个文本文档中
Note
Reference
 http://www.cplusplus.com/reference/string/string/find_last_of/
 http://www.cplusplus.com/reference/ctime/clock/
 http://www.cplusplus.com/reference/ctime/localtime/
Definition at line 37 of file test0.cc.
References data_file_name(), Tree::binaryTree< T, Comparator >::delLeft(), Tree::GenTreeData(), and Tree::print_test_result().