src/ch6_5.cc File Reference
测试：判断两棵二叉树是否相同
#include `binaryTree.hh`
#include <ctime>
#include <fstream>
#include <string>
Functions
const std::string data_file_name (`ch6_5.result`)
保存测试数据的文件名
static bool GenTreeData (const char *_file_path=`./test0.txt`, const char *empty_flag=`@`)
生成一个文件，内容是一棵二叉树的层次遍历
template<typename T , typename Comparator >
static void print_test_result (const Tree::binaryTree< T, Comparator > &tree_original, const typename Tree::binaryTree< T, Comparator >::value_type &flag, std::ostream &out=std::cout)
(测试用)将二叉树类的多种方法的输出插到输出流
int main (int argc, char const *argv[])
template<class T , typename Comparator >
void print_test_result (const Tree::binaryTree< T, Comparator > &tree_original, const typename Tree::binaryTree< T, Comparator >::value_type &flag, std::ostream &out)
(测试用)将二叉树类的多种方法的输出插到输出流
Detailed Description
测试：判断两棵二叉树是否相同
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-04-28
Copyright
Copyright (c) 2020
See the file LICENSE in the top directory of this distribution for more information.
Function Documentation
data_file_name()
const std::string data_file_name (`ch6_5.result`)
保存测试数据的文件名
Referenced by main().
GenTreeData()
bool GenTreeData (const char * _file_path = `./test0.txt`, const char * empty_flag = `@`) [static]
生成一个文件，内容是一棵二叉树的层次遍历
Parameters
_file_path 文件路径
empty_flag 空结点标记
首先询问是否删除同名文件（若有）。 \然后判断文件是否存在且可读，若是，则不做任何操作； \若否，则尝试新建文件。 \函数返回true，只保证文件file_path存在，不保证其可读。
Returns
true 文件已存在，或生成成功
false 文件生成失败
Definition at line 159 of file ch6_5.cc.
Referenced by main().
main()
int main (int argc, char const * argv[])
Definition at line 51 of file ch6_5.cc.
References Tree::binaryTree< T, Comparator >::createTree(), data_file_name(), Tree::binaryTree< T, Comparator >::delLeft(), Tree::binaryTree< T, Comparator >::delRight(), GenTreeData(), print_test_result(), and Tree::binaryTree< T, Comparator >::swaplr().
print_test_result() [1/2]
template<class T , typename Comparator >
void print_test_result (const Tree::binaryTree< T, Comparator > & binary_tree, const typename Tree::binaryTree< T, Comparator >::value_type & flag, std::ostream & out = std::cout)
(测试用)将二叉树类的多种方法的输出插到输出流
Template Parameters
T 二叉树存储的数据的类型
Comparator 函数对象，用于比较T类型的数据：lhs < rhs
Note
要求重载bool operator(const T &lhs, const T &rhs)
Parameters
binary_tree 二叉树类的对象
flag 类T的对象，表示空结点的特殊标记
out 输出流对象，要求是ostream类及其派生类的对象，如std::cout，或ofstream类的对象
Definition at line 211 of file ch6_5.cc.
References Tree::binaryTree< T, Comparator >::CountDegreeTwo(), Tree::binaryTree< T, Comparator >::height(), Tree::binaryTree< T, Comparator >::height_loop(), Tree::binaryTree< T, Comparator >::inOrder(), Tree::binaryTree< T, Comparator >::inOrder_loop(), Tree::binaryTree< T, Comparator >::isCompleteTree(), Tree::binaryTree< T, Comparator >::isFullBinaryTree(), Tree::binaryTree< T, Comparator >::levelOrder(), Tree::binaryTree< T, Comparator >::postOrder(), Tree::binaryTree< T, Comparator >::postOrder_loop(), Tree::binaryTree< T, Comparator >::preOrder(), Tree::binaryTree< T, Comparator >::preOrder_loop(), Tree::printBinaryTree(), Tree::binaryTree< T, Comparator >::size(), and Tree::binaryTree< T, Comparator >::size_loop().
print_test_result() [2/2]
template<typename T , typename Comparator >
static void print_test_result (const Tree::binaryTree< T, Comparator > & tree_original, const typename Tree::binaryTree< T, Comparator >::value_type & flag, std::ostream & out = std::cout) [static]
(测试用)将二叉树类的多种方法的输出插到输出流
Template Parameters
T 二叉树存储的数据的类型
Comparator 函数对象，用于比较T类型的数据：lhs < rhs
Note
要求重载bool operator(const T &lhs, const T &rhs)
Parameters
tree_original 二叉树类的对象
flag 类T的对象，表示空结点的特殊标记
out 输出流对象，要求是ostream类及其派生类的对象，如std::cout，或ofstream类的对象
Template Parameters
T 二叉树存储的数据的类型
Comparator 函数对象，用于比较T类型的数据：lhs < rhs
Note
要求重载bool operator(const T &lhs, const T &rhs)
Parameters
binary_tree 二叉树类的对象
flag 类T的对象，表示空结点的特殊标记
out 输出流对象，要求是ostream类及其派生类的对象，如std::cout，或ofstream类的对象
Definition at line 175 of file ch6_1.cc.
Referenced by main().