src/ch7_1.cc File Reference
程序设计题第1题：实现最大堆
#include `BinaryHeap.h`
#include <cstdlib>
#include <ctime>
#include <fstream>
Functions
int main (int argc, char const *argv[])
测试程序
Detailed Description
程序设计题第1题：实现最大堆
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-07-04
Copyright
Copyright (c) 2020
See the file LICENSE in the top directory of this distribution for more information.
Function Documentation
main()
int main (int argc, char const * argv[])
测试程序
Parameters
argc 参数个数
argv 参数数组
Returns
int 返回值
Warning
要求.exe对其所在的目录有读写权限
部分测试结果将输出到一个文本文档中
Definition at line 28 of file ch7_1.cc.
References List::seqList< T >::push_back(), Queue::BinaryHeap< Comparable, Compare >::top(), and List::seqList< T >::traverse().