src/ch7_7.cc File Reference
程序设计题第7题：实现基于最小堆的整型的优先级队列，包含功能findMin(x) 和 decreaseKey(i, value)
#include `BinaryHeap.h`
#include <algorithm>
#include <climits>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <vector>
Classes
class Queue::priority_queue_int
基于最小堆的整型的优先级队列类
Namespaces
 Queue
队列
Functions
int main (int argc, char const *argv[])
测试程序
Detailed Description
程序设计题第7题：实现基于最小堆的整型的优先级队列，包含功能findMin(x) 和 decreaseKey(i, value)
Author
Guorui Wei (313017602@qq.com)
Version
0.1
Date
2020-07-04
Copyright
Copyright (c) 2020
See the file LICENSE in the top directory of this distribution for more information.
Function Documentation
main()
int main (int argc, char const * argv[])
测试程序
Parameters
argc 参数个数
argv 参数数组
Returns
int 返回值
Warning
要求.exe对其所在的目录有读写权限
部分测试结果将输出到一个文本文档中
Definition at line 70 of file ch7_7.cc.
References Queue::priority_queue_int::findMin(), Queue::priority_queue_int::increaseKey(), Queue::BinaryHeap< Comparable, Compare >::print_heap(), List::seqList< T >::push_back(), Queue::BinaryHeap< Comparable, Compare >::size(), Queue::BinaryHeap< Comparable, Compare >::top(), and List::seqList< T >::traverse().