Priority_queue::BinaryHeap< Comparable > Class Template Reference
#include <BinaryHeap.h>
Public Member Functions
BinaryHeap (size_t capacity=100)
Construct a new Binary Heap object.
BinaryHeap (const List::seqList< Comparable > &items)
Construct a new Binary Heap object.
~BinaryHeap ()=default
Destroy the Binary Heap object.
bool empty () const
判队空
const Comparable & top () const
返回队头元素值
void pop ()
队头元素出队
void pop (Comparable *minItem)
队头元素出队，保存在minItem指向的空间中
void push (const Comparable &x)
将x入队
void clear ()
清空队列
Private Member Functions
void buildHeap ()
Establish heap order property from an arbitrary arrangement of items. Run in linear time.
void percolateDown (size_t hole)
Internal method to percolate down in the heap.
Private Attributes
size_t current_size_
Number of elements in heap.
List::seqList< Comparable > array_
The heap array.
Detailed Description
template<typename Comparable>
class Priority_queue::BinaryHeap< Comparable >
Definition at line 20 of file BinaryHeap.h.
Constructor & Destructor Documentation
BinaryHeap() [1/2]
template<typename Comparable >
Priority_queue::BinaryHeap< Comparable >::BinaryHeap (size_t capacity = 100) [explicit]
Construct a new Binary Heap object.
Parameters
capacity 容器的初始容量.
数据范围array[1] ~ array[capacity]
Definition at line 116 of file BinaryHeap.h.
BinaryHeap() [2/2]
template<typename Comparable >
Priority_queue::BinaryHeap< Comparable >::BinaryHeap (const List::seqList< Comparable > & items) [explicit]
Construct a new Binary Heap object.
Parameters
items 容器的初值来源
Definition at line 150 of file BinaryHeap.h.
References List::seqList< T >::size().
 BinaryHeap()
template<typename Comparable >
Priority_queue::BinaryHeap< Comparable >::~BinaryHeap () [default]
Destroy the Binary Heap object.
Member Function Documentation
buildHeap()
template<typename Comparable >
void Priority_queue::BinaryHeap< Comparable >::buildHeap [private]
Establish heap order property from an arbitrary arrangement of items. Run in linear time.
Definition at line 162 of file BinaryHeap.h.
clear()
template<typename Comparable >
void Priority_queue::BinaryHeap< Comparable >::clear
清空队列
Definition at line 213 of file BinaryHeap.h.
empty()
template<typename Comparable >
bool Priority_queue::BinaryHeap< Comparable >::empty
判队空
Returns
true 空
false 非空
Definition at line 122 of file BinaryHeap.h.
Referenced by main().
percolateDown()
template<typename Comparable >
void Priority_queue::BinaryHeap< Comparable >::percolateDown (size_t hole) [private]
Internal method to percolate down in the heap.
Parameters
hole the index at which the percolate begins.
Definition at line 171 of file BinaryHeap.h.
pop() [1/2]
template<typename Comparable >
void Priority_queue::BinaryHeap< Comparable >::pop
队头元素出队
Definition at line 196 of file BinaryHeap.h.
Referenced by main().
pop() [2/2]
template<typename Comparable >
void Priority_queue::BinaryHeap< Comparable >::pop (Comparable * minItem)
队头元素出队，保存在minItem指向的空间中
Parameters
minItem 指向元素类型的指针
Definition at line 204 of file BinaryHeap.h.
push()
template<typename Comparable >
void Priority_queue::BinaryHeap< Comparable >::push (const Comparable & x)
将x入队
Parameters
x 新元素
Definition at line 134 of file BinaryHeap.h.
top()
template<typename Comparable >
const Comparable & Priority_queue::BinaryHeap< Comparable >::top
返回队头元素值
Returns
const Comparable& 队头元素（最小）
Definition at line 128 of file BinaryHeap.h.
Referenced by main().
Member Data Documentation
array_
template<typename Comparable >
List::seqList<Comparable> Priority_queue::BinaryHeap< Comparable >::array_ [private]
The heap array.
数据范围[1, current_size]
Definition at line 34 of file BinaryHeap.h.
current_size_
template<typename Comparable >
size_t Priority_queue::BinaryHeap< Comparable >::current_size_ [private]
Number of elements in heap.
Definition at line 27 of file BinaryHeap.h.
The documentation for this class was generated from the following file:
include/BinaryHeap.h