List::seqList< T > Class Template Reference
#include <seqList.h>
Classes
class const_iterator
class iterator
Public Member Functions
seqList (size_t initSize=10)
Construct a new seq List object.
seqList (const seqList< T > &rhs)
Construct a new seq List object.
seqList (seqList< T > &&rvalue)
Construct a new seq List object.
seqList (const std::initializer_list< T > &init_list)
Construct a new seq List object.
virtual ~seqList ()
Destroy the seq List object.
virtual void clear ()
virtual int length () const
virtual void insert (int i, const T &obj)
virtual void remove (int i)
virtual int search (const T &obj) const
virtual T visit (int i) const
virtual void traverse (std::ostream &out=std::cout) const
T & operator[] (size_t index)
下标访问（mutator）
const T & operator[] (size_t index) const
下标访问（accessor）
void push_back (const T &x)
在表尾插入新元素
void push_back (T &&x)
在表尾插入新元素
void pop_back ()
删除表尾元素
size_t size () const
返回线性表的当前元素个数，即长度
T & front ()
Access first element. Returns a reference to the first element in the vector.
const T & front () const
Access first element. Returns a reference to the first element in the vector.
T & back ()
Access last element. Returns a reference to the last element in the vector.
const T & back () const
Access last element. Returns a reference to the last element in the vector.
void resize (size_t n)
Change size Resizes the container so that it contains n elements.
virtual iterator begin ()
virtual const_iterator begin () const
virtual iterator end ()
virtual const_iterator end () const
Private Member Functions
void doubleSpace ()
Private Attributes
T * data
size_t currentLength
size_t maxSize
Detailed Description
template<typename T>
class List::seqList< T >
Definition at line 23 of file seqList.h.
Constructor & Destructor Documentation
seqList() [1/4]
template<class T >
List::seqList< T >::seqList (size_t initSize = 10)
Construct a new seq List object.
Parameters
initSize 初始容量
Definition at line 261 of file seqList.h.
seqList() [2/4]
template<class T >
List::seqList< T >::seqList (const seqList< T > & rhs)
Construct a new seq List object.
Parameters
rhs 复制源对象
Definition at line 289 of file seqList.h.
seqList() [3/4]
template<class T >
List::seqList< T >::seqList (seqList< T > && rvalue)
Construct a new seq List object.
Parameters
rvalue 复制源对象
Definition at line 280 of file seqList.h.
seqList() [4/4]
template<class T >
List::seqList< T >::seqList (const std::initializer_list< T > & init_list)
Construct a new seq List object.
Parameters
init_list braced-init-list
Definition at line 268 of file seqList.h.
 seqList()
template<class T >
List::seqList< T >::~seqList [virtual]
Destroy the seq List object.
Definition at line 221 of file seqList.h.
Member Function Documentation
back() [1/2]
template<class T >
const T & List::seqList< T >::back
Access last element. Returns a reference to the last element in the vector.
Returns
T& A reference to the last element in the vector. If the vector object is const-qualified, the function returns a const_reference. Otherwise, it returns a reference.
Definition at line 402 of file seqList.h.
back() [2/2]
template<typename T >
const T& List::seqList< T >::back () const
Access last element. Returns a reference to the last element in the vector.
Returns
T& A reference to the last element in the vector. If the vector object is const-qualified, the function returns a const_reference. Otherwise, it returns a reference.
begin() [1/2]
template<typename T >
virtual iterator List::seqList< T >::begin () [inline], [virtual]
Definition at line 213 of file seqList.h.
begin() [2/2]
template<typename T >
virtual const_iterator List::seqList< T >::begin () const [inline], [virtual]
Definition at line 214 of file seqList.h.
clear()
template<class T >
void List::seqList< T >::clear [virtual]
Implements List::List< T >.
Definition at line 227 of file seqList.h.
doubleSpace()
template<class T >
void List::seqList< T >::doubleSpace [private]
Definition at line 307 of file seqList.h.
end() [1/2]
template<typename T >
virtual iterator List::seqList< T >::end () [inline], [virtual]
Definition at line 215 of file seqList.h.
end() [2/2]
template<typename T >
virtual const_iterator List::seqList< T >::end () const [inline], [virtual]
Definition at line 216 of file seqList.h.
front() [1/2]
template<class T >
const T & List::seqList< T >::front
Access first element. Returns a reference to the first element in the vector.
Returns
T& A reference to the first element in the vector container. If the vector object is const-qualified, the function returns a const_reference. Otherwise, it returns a reference.
Definition at line 390 of file seqList.h.
front() [2/2]
template<typename T >
const T& List::seqList< T >::front () const
Access first element. Returns a reference to the first element in the vector.
Returns
T& A reference to the first element in the vector container. If the vector object is const-qualified, the function returns a const_reference. Otherwise, it returns a reference.
insert()
template<class T >
void List::seqList< T >::insert (int i, const T & obj) [virtual]
Implements List::List< T >.
Definition at line 318 of file seqList.h.
Referenced by List::operator+().
length()
template<class T >
int List::seqList< T >::length [virtual]
Implements List::List< T >.
Definition at line 233 of file seqList.h.
Referenced by List::operator+().
operator[]() [1/2]
template<class T >
T & List::seqList< T >::operator[] (size_t index)
下标访问（mutator）
Parameters
index 下标
Returns
T& 元素
Definition at line 352 of file seqList.h.
operator[]() [2/2]
template<class T >
const T & List::seqList< T >::operator[] (size_t index) const
下标访问（accessor）
Parameters
index 下标
Returns
const T& 元素
Definition at line 360 of file seqList.h.
pop_back()
template<class T >
void List::seqList< T >::pop_back
删除表尾元素
Definition at line 384 of file seqList.h.
push_back() [1/2]
template<class T >
void List::seqList< T >::push_back (const T & x)
在表尾插入新元素
Parameters
x 新元素
Definition at line 368 of file seqList.h.
push_back() [2/2]
template<class T >
void List::seqList< T >::push_back (T && x)
在表尾插入新元素
Parameters
x 新元素
Definition at line 376 of file seqList.h.
remove()
template<class T >
void List::seqList< T >::remove (int i) [virtual]
Implements List::List< T >.
Definition at line 330 of file seqList.h.
resize()
template<class T >
void List::seqList< T >::resize (size_t n)
Change size Resizes the container so that it contains n elements.
Parameters
n New container size, expressed in number of elements.
Definition at line 414 of file seqList.h.
search()
template<class T >
int List::seqList< T >::search (const T & obj) const [virtual]
Implements List::List< T >.
Definition at line 297 of file seqList.h.
size()
template<class T >
size_t List::seqList< T >::size
返回线性表的当前元素个数，即长度
Returns
size_t 当前线性表长，即元素个数
Definition at line 239 of file seqList.h.
Referenced by Priority_queue::BinaryHeap< Comparable >::BinaryHeap().
traverse()
template<class T >
void List::seqList< T >::traverse (std::ostream & out = std::cout) const [virtual]
Definition at line 251 of file seqList.h.
Referenced by main().
visit()
template<class T >
T List::seqList< T >::visit (int i) const [virtual]
Implements List::List< T >.
Definition at line 245 of file seqList.h.
Referenced by List::operator+().
Member Data Documentation
currentLength
template<typename T >
size_t List::seqList< T >::currentLength [private]
Definition at line 27 of file seqList.h.
Referenced by List::seqList< Comparable >::end().
data
template<typename T >
T* List::seqList< T >::data [private]
Definition at line 26 of file seqList.h.
Referenced by List::seqList< Comparable >::begin(), and List::seqList< Comparable >::end().
maxSize
template<typename T >
size_t List::seqList< T >::maxSize [private]
Definition at line 28 of file seqList.h.
Referenced by List::seqList< Comparable >::seqList().
The documentation for this class was generated from the following file:
include/seqList.h