cmake/func/func.h File Reference
#include <iostream>
#include <string>
Functions
int fun1 (std::string str=`fun1\t`)
int fun2 (std::string str=`fun2\t`)
int fun3 (std::string str=`fun3\t`)
Function Documentation
fun1()
int fun1 (std::string str = `fun1\t`)
Definition at line 3 of file fun1.cxx.
Referenced by main().
fun2()
int fun2 (std::string str = `fun2\t`)
Definition at line 3 of file fun2.cxx.
Referenced by main().
fun3()
int fun3 (std::string str = `fun3\t`)
Definition at line 3 of file fun3.cxx.
Referenced by main().