cmake/main.cxx File Reference
#include `func.h`
#include `mainConfig.h`
Functions
int main (int argc, char const *argv[])
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 4 of file main.cxx.
References fun1(), fun2(), and fun3().