src/test0.cc File Reference
#include `Queue.h`
#include <iostream>
#include <string>
Classes
struct data_t
用于测试队列的简单类
Functions
int main (int argc, char const *argv[])
测试队列类的基本功能
Function Documentation
main()
int main (int argc, char const * argv[])
测试队列类的基本功能
Parameters
argc 命令行参数的数目
argv 命令行参数的内容
Returns
int 0-正常结束, 1-异常终止
Note
此例程不使用命令行参数
测试方法: 对3种队列, 先入队5个元素, 再全部出队 < 循环队列
< 链接队列
< 顺序队列
< 测试数据
< 复制入队(enQueue()未实现右值版本)
< 移动入队
< 复制入队
Definition at line 60 of file test0.cc.
References Queue::vecQueue< T >::deQueue(), Queue::seqQueue< T >::deQueue(), Queue::vecQueue< T >::empty(), Queue::seqQueue< T >::empty(), Queue::vecQueue< T >::enQueue(), Queue::seqQueue< T >::enQueue(), Queue::linkQueue< T >::front(), Queue::linkQueue< T >::isEmpty(), Queue::linkQueue< T >::pop(), data_t::prn(), Queue::linkQueue< T >::push(), Queue::vecQueue< T >::size(), Queue::seqQueue< T >::size(), and Queue::linkQueue< T >::size().